name: 'Fast Forward Merge'
description: 'merge fast forwardable on PR'
inputs:
  GITHUB_TOKEN:
    description: 'Automatically provided token, that can be used to authenticate on behalf of the GitHub action, with permissions limited to the repository that contains your workflow'
  SSH_PRIVATE_KEY:
    description: 'deploy key for push'

runs:
  using: "composite"
  steps:  
      - uses: actions-cool/check-user-permission@v2
        with:
          require: 'write'
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
          persist-credentials: true
      - name: Fast Forward PR
        id: ffaction
        uses: APN-Pucky/fast-forward-js-action@master
        with:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
      - name: FF Merge
        run: |
          git checkout ${{ steps.ffaction.outputs.ffbase }}
          git merge --ff-only ${{ steps.ffaction.outputs.ffbase }} ${{ steps.ffaction.outputs.ffsha }}
        shell: bash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ steps.ffaction.outputs.ffbase }}