name: 'Fast Forward'
description: 'Merge pull request using fast forward only, if possible, moving base branch (target branch) to head branch (source branch)'
inputs:
  GITHUB_TOKEN:
    description: 'Automatically provided token, that can be used to authenticate on behalf of the GitHub action, with permissions limited to the repository that contains your workflow'
  PAT:
    description: 'Push with PAT instead of GITHUB_TOKEN.'
    default: '0'
runs:
  using: "composite"
  steps:  
      # To use this repository's private action, you must check out the repository
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: APN-Pucky/fast-forward-action/label@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      - uses: APN-Pucky/fast-forward-action/merge@main
        if: github.event.issue.pull_request != '' && startsWith(github.event.comment.body, '/fast-forward') 
        with:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          PAT: ${{ inputs.PAT }}
      - name: push -> clean ff
        uses: APN-Pucky/actions-label-merge-conflict@main
        if: github.event.issue.pull_request == '' || false == startsWith(github.event.comment.body, '/fast-forward') 
        with:
          dirtyLabel: "PR: FF needs rebase"
          removeOnDirtyLabel: "fast-forward"
          repoToken: "${{ inputs.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
# TODO
#branding:
#  icon: 'git-merge'  
#  color: 'green'
