name: 'Fast Forward'
description: 'Merge pull request using fast forward only, if possible, moving base branch (target branch) to head branch (source branch)'
inputs:
  GITHUB_TOKEN:
    description: 'Automatically provided token, that can be used to authenticate on behalf of the GitHub action, with permissions limited to the repository that contains your workflow'
  success_message:
    description: 'Generic success message, will be commented on the pull request, if pull-request fast forward succeeds.'
  failure_message:
    description: 'Generic failure message, Will be commented on the pull request, if pull-request fast forward fails.'
  update_status:
    description: 'Optional, if true, the status API is used to set failure or success as a state for the commit, which can be used to gate merging. Default value is false.'
  failure_message_same_stage_and_prod:
    description: 'Optional, failure message, when pull-request fast forward fails, and staging branch equals production branch'
  failure_message_diff_stage_and_prod:
    description: 'Optional, failure message, when pull-request fast forward fails, and staging branch and production branch are at different commits'
  production_branch:
    description: 'Optional, production branch name. Default value is master.'
  staging_branch:
    description: 'Optional, staging or preproduction branch name. Default value is staging.'
runs:
  using: "composite"
  steps:  
      # To use this repository's private action, you must check out the repository
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Basic use case example
      - uses: ./label
        if: ${{ github.event_name == 'pull_request' }} 
        with:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "fast-forward"
          repoToken: "${{ inputs.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
      - name: Fast Forward PR
        if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward') 
        id: ff-action
        uses: APN-Pucky/fast-forward-js-action@master
        with:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
# TODO
#branding:
#  icon: 'git-merge'  
#  color: 'green'
